export enum SubKeyEnum {
    GTC_EVENT_KEY = "GTC_EVENT_SUB_KEY",
    GTC_DATA_GRAM_KEY = "GTC_DATA_GRAM_KEY",
    NODE_INFO_LIST_KEY = "NODE_INFO_LIST_KEY",
    NEW_DATA_REFRESH = "NEW_DATA_REFRESH",

    LAUNCH_OK = "LAUNCH_OK",
    ATS_LOAD_OK = "ATS_LOAD_OK",
    ATS_START_OK = "ATS_START_OK",
    ATS_JUMP_ACTION = "ATS_JUMP_ACTION",
    ATS_TERMINATE_ABNORMAL = "ATS_TERMINATE_ABNORMAL",
    ATS_TERMINATE = "ATS_TERMINATE",
}