import {JsonRpcEventEnum} from "./JsonRpcEventEnum";

/**
 * 远程调用方法
 */
export enum JsonRpcMethodEnum {
    EVENT_LOG = JsonRpcEventEnum.EVENT + ".log",
    DATAGRAM_LIVE_DATA = JsonRpcEventEnum.DATAGRAM + ".liveData",
    DATAGRAM_ANALYZE_DATA = JsonRpcEventEnum.DATAGRAM + ".analyzeData",
    CALL_GET_DLL_VER = JsonRpcEventEnum.CALL + ".getDllVer",
    REPLY_GET_DLL_VER = JsonRpcEventEnum.REPLY + ".getDllVer",
    CALL_GET_CARD_NUMBER = JsonRpcEventEnum.CALL + ".getCardNumber",
    REPLY_GET_CARD_NUMBER = JsonRpcEventEnum.REPLY + ".getCardNumber",
    CALL_LAUNCH = JsonRpcEventEnum.CALL + ".launch",
    REPLY_LAUNCH = JsonRpcEventEnum.REPLY + ".launch",
    CALL_GET_DIGITAL_LIST = JsonRpcEventEnum.CALL + ".getDigitalList",
    CALL_GET_SWITCH_LIST = JsonRpcEventEnum.CALL + ".getSwitchList",
    REPLY_GET_DIGITAL_LIST = JsonRpcEventEnum.REPLY + ".getDigitalList",
    REPLY_GET_SWITCH_LIST = JsonRpcEventEnum.REPLY + ".getSwitchList",
    CALL_SET_REF_GEN_SLOPE= JsonRpcEventEnum.CALL + ".setRefGenSlope",
    REPLY_SET_REF_GEN_SLOPE = JsonRpcEventEnum.REPLY + ".setRefGenSlope",
    CALL_OPEN_LOOP_STOP = JsonRpcEventEnum.CALL + ".openLoopStop",
    CALL_CLOSE_LOOP_STOP = JsonRpcEventEnum.CALL + ".closeLoopStop",
    CALL_RESET_WAVE_COUNT = JsonRpcEventEnum.CALL + ".resetWaveCount",
    REPLY_OPEN_LOOP_STOP = JsonRpcEventEnum.REPLY + ".openLoopStop",
    REPLY_CLOSE_LOOP_STOP = JsonRpcEventEnum.REPLY + ".closeLoopStop",
    REPLY_RESET_WAVE_COUNT = JsonRpcEventEnum.REPLY + ".resetWaveCount",
    CALL_GET_MAX_SCALE = JsonRpcEventEnum.CALL + ".getMaxScale",
    REPLY_GET_MAX_SCALE = JsonRpcEventEnum.REPLY + ".getMaxScale",
    CALL_SET_PROTECTED_LIMIT = JsonRpcEventEnum.CALL + ".setProtectLimit",
    REPLY_SET_PROTECTED_LIMIT = JsonRpcEventEnum.REPLY + ".setProtectLimit",
    CALL_CLEAR_TO_ZERO = JsonRpcEventEnum.CALL + ".clearToZero",
    REPLY_CLEAR_TO_ZERO = JsonRpcEventEnum.REPLY + ".clearToZero",
    CALL_SWITCH_DIGITAL_OUT = JsonRpcEventEnum.CALL + ".switchDigitalOut",
    REPLY_SWITCH_DIGITAL_OUT = JsonRpcEventEnum.REPLY + ".switchDigitalOut",
    CALL_CLOSE = JsonRpcEventEnum.CALL + ".close",
    REPLY_CLOSE = JsonRpcEventEnum.REPLY + ".close",
    CALL_GET_PRODUCT_INFO = JsonRpcEventEnum.CALL + ".getProductInfo",
    REPLY_GET_PRODUCT_INFO = JsonRpcEventEnum.REPLY + ".getProductInfo",
    CALL_ATS_LOAD = JsonRpcEventEnum.CALL + ".atsLoad",
    CALL_ATS_START = JsonRpcEventEnum.CALL + ".atsStart",
    CALL_ATS_TERMINATE = JsonRpcEventEnum.CALL + ".atsTerminate",
    CALL_ATS_SET_PARAM = JsonRpcEventEnum.CALL + ".atsSetParam",
    CALL_ATS_PUSH_BUTTON = JsonRpcEventEnum.CALL + ".atsPushButton",
    REPLY_ATS_LOAD = JsonRpcEventEnum.REPLY + ".atsLoad",
    REPLY_ATS_START = JsonRpcEventEnum.REPLY + ".atsStart",
    REPLY_ATS_TERMINATE = JsonRpcEventEnum.REPLY + ".atsTerminate",
    REPLY_ATS_SET_PARAM = JsonRpcEventEnum.REPLY + ".atsSetParam",
    REPLY_ATS_PUSH_BUTTON = JsonRpcEventEnum.REPLY + ".atsPushButton",
}